/**
 * Boss Registry Barrel
 *
 * Importing this module triggers side-effect registration of all boss modules.
 */

// Side-effect imports — register boss modules
import './boomstick'
import './madDog'

// Re-export registry API
export { getBoss, isBoss, allBosses, registerBoss } from './registry'
export type { BossModule } from './registry'

// Re-export boss constants needed by external consumers (SnapshotIngestor, tests, etc.)
export {
  BOOMSTICK_HP,
  BOOMSTICK_RADIUS,
  BOOMSTICK_DAMAGE,
  BOOMSTICK_BUDGET_COST,
  BOOMSTICK_TRANSITION_IFRAMES,
  BOOMSTICK_PHASE_2_TELEGRAPH,
  BOOMSTICK_PHASE_2_RECOVERY,
  BOOMSTICK_PHASE_2_COOLDOWN,
  BOOMSTICK_PHASE_2_FAN_BULLETS,
  BOOMSTICK_PHASE_2_SUMMON_SWARMERS,
  BOOMSTICK_PHASE_2_SUMMON_ROGUES,
  BOOMSTICK_PHASE_3_TELEGRAPH,
  BOOMSTICK_PHASE_3_RECOVERY,
  BOOMSTICK_PHASE_3_COOLDOWN,
  BOOMSTICK_PHASE_3_FAN_BULLETS,
  BOOMSTICK_PHASE_3_SUMMON_SWARMERS,
  BOOMSTICK_PHASE_3_SUMMON_ROGUES,
  BOOMSTICK_BULLET_COUNT,
  BOOMSTICK_RING_BULLET_COUNT,
  BOOMSTICK_PHASE_3_RING_BULLETS,
  BOOMSTICK_BOOM_DAMAGE,
  BOOMSTICK_BOOM_RADIUS,
  BOOMSTICK_BOOM_FUSE,
} from './boomstick'

export {
  MAD_DOG_HP,
  MAD_DOG_RADIUS,
  MAD_DOG_P1_SPEED,
  MAD_DOG_P2_SPEED,
  MAD_DOG_P3_SPEED,
  MAD_DOG_P1_COOLDOWN,
  MAD_DOG_P2_COOLDOWN,
  MAD_DOG_P3_COOLDOWN,
  MAD_DOG_TRANSITION_IFRAMES,
  MAD_DOG_P3_SUMMON_SWARMERS,
  MAD_DOG_SWEEP_DAMAGE,
  MAD_DOG_SLAM_DAMAGE,
  MAD_DOG_WHIRLWIND_DAMAGE,
  MAD_DOG_LUNGE_DAMAGE,
  MAD_DOG_GROUND_POUND_DAMAGE,
  MAD_DOG_GROUND_POUND_SHOCKWAVE_DAMAGE,
  MAD_DOG_GROUND_POUND_CADENCE,
  MAD_DOG_SWEEP_ARC_P1P2,
  MAD_DOG_SWEEP_ARC_P3,
  MAD_DOG_GROUND_CRACK_SPEED_MUL,
} from './madDog'
