/**
 * Boss Registry Barrel
 *
 * Importing this module triggers side-effect registration of all boss modules.
 */

// Side-effect imports — register boss modules
import './boomstick'
import './madDog'
import './daltonBoys'
import './coyoteJane'
import './hollowMan'
import './oldScratch'

// Re-export registry API
export { getBoss, isBoss, allBosses, registerBoss } from './registry'
export type { BossModule } from './registry'

// Re-export boss constants needed by external consumers (SnapshotIngestor, tests, etc.)
export {
  BOOMSTICK_HP,
  BOOMSTICK_RADIUS,
  BOOMSTICK_DAMAGE,
  BOOMSTICK_BUDGET_COST,
  BOOMSTICK_TRANSITION_IFRAMES,
  BOOMSTICK_PHASE_2_TELEGRAPH,
  BOOMSTICK_PHASE_2_RECOVERY,
  BOOMSTICK_PHASE_2_COOLDOWN,
  BOOMSTICK_PHASE_2_FAN_BULLETS,
  BOOMSTICK_PHASE_2_SUMMON_SWARMERS,
  BOOMSTICK_PHASE_2_SUMMON_ROGUES,
  BOOMSTICK_PHASE_3_TELEGRAPH,
  BOOMSTICK_PHASE_3_RECOVERY,
  BOOMSTICK_PHASE_3_COOLDOWN,
  BOOMSTICK_PHASE_3_FAN_BULLETS,
  BOOMSTICK_PHASE_3_SUMMON_SWARMERS,
  BOOMSTICK_PHASE_3_SUMMON_ROGUES,
  BOOMSTICK_BULLET_COUNT,
  BOOMSTICK_RING_BULLET_COUNT,
  BOOMSTICK_PHASE_3_RING_BULLETS,
  BOOMSTICK_BOOM_DAMAGE,
  BOOMSTICK_BOOM_RADIUS,
  BOOMSTICK_BOOM_FUSE,
} from './boomstick'

export {
  DALTON_EMMETT_HP,
  DALTON_BOB_HP,
  DALTON_EMMETT_SPEED,
  DALTON_BOB_SPEED,
  DALTON_BUCKSHOT_DAMAGE,
  DALTON_DEADSHOT_DAMAGE,
  DALTON_BULL_RUSH_DAMAGE,
  DALTON_COVERING_FIRE_DAMAGE,
  DALTON_ENRAGE_SPEED_MUL,
  DALTON_ENRAGE_COOLDOWN_MUL,
  DALTON_GROUP_KEY,
  DALTON_TRANSITION_IFRAMES,
} from './daltonBoys'

export {
  MAD_DOG_HP,
  MAD_DOG_RADIUS,
  MAD_DOG_P1_SPEED,
  MAD_DOG_P2_SPEED,
  MAD_DOG_P3_SPEED,
  MAD_DOG_P1_COOLDOWN,
  MAD_DOG_P2_COOLDOWN,
  MAD_DOG_P3_COOLDOWN,
  MAD_DOG_TRANSITION_IFRAMES,
  MAD_DOG_P3_SUMMON_SWARMERS,
  MAD_DOG_SWEEP_DAMAGE,
  MAD_DOG_SLAM_DAMAGE,
  MAD_DOG_WHIRLWIND_DAMAGE,
  MAD_DOG_LUNGE_DAMAGE,
  MAD_DOG_GROUND_POUND_DAMAGE,
  MAD_DOG_GROUND_POUND_SHOCKWAVE_DAMAGE,
  MAD_DOG_GROUND_POUND_CADENCE,
  MAD_DOG_SWEEP_ARC_P1P2,
  MAD_DOG_SWEEP_ARC_P3,
  MAD_DOG_GROUND_CRACK_SPEED_MUL,
} from './madDog'

export {
  COYOTE_JANE_HP,
  COYOTE_JANE_RADIUS,
  COYOTE_JANE_P1_SPEED,
  COYOTE_JANE_P2_SPEED,
  COYOTE_JANE_P3_SPEED,
  COYOTE_JANE_P1_COOLDOWN,
  COYOTE_JANE_P2_COOLDOWN,
  COYOTE_JANE_P3_COOLDOWN,
  COYOTE_JANE_P1_TELEGRAPH,
  COYOTE_JANE_P2_TELEGRAPH,
  COYOTE_JANE_P3_TELEGRAPH,
  COYOTE_JANE_P3_RECOVERY,
  COYOTE_JANE_TRANSITION_IFRAMES,
  COYOTE_JANE_RIFLE_DAMAGE,
  COYOTE_JANE_HIP_DAMAGE,
  COYOTE_JANE_BEAR_TRAP_DAMAGE,
  COYOTE_JANE_BEAR_TRAP_RADIUS,
  COYOTE_JANE_BEAR_TRAP_IMMOBILIZE,
  COYOTE_JANE_BEAR_TRAP_HP,
  COYOTE_JANE_BEAR_TRAP_COOLDOWN,
  COYOTE_JANE_BEAR_TRAP_MAX,
  COYOTE_JANE_CALTROP_RADIUS,
  COYOTE_JANE_CALTROP_SLOW,
  COYOTE_JANE_CALTROP_DURATION,
  COYOTE_JANE_CALTROP_COOLDOWN,
  COYOTE_JANE_P3_SUMMON_COYOTES,
  COYOTE_JANE_DASH_SPEED,
  COYOTE_JANE_DASH_DURATION,
  COYOTE_JANE_P1_REPOSITION_COOLDOWN,
  COYOTE_JANE_P2_REPOSITION_COOLDOWN,
  COYOTE_JANE_WHISTLE_INITIAL_COOLDOWN,
  COYOTE_JANE_WHISTLE_RESET_COOLDOWN,
  COYOTE_JANE_WHISTLE_SUMMON_COUNT,
  COYOTE_JANE_TRIPWIRE_DAMAGE,
  COYOTE_JANE_TRIPWIRE_EXPLOSION_RADIUS,
} from './coyoteJane'

export {
  HOLLOW_MAN_HP,
  HOLLOW_MAN_RADIUS,
  HOLLOW_MAN_P1_SPEED,
  HOLLOW_MAN_TRANSITION_IFRAMES,
  HOLLOW_MAN_P1_TELEPORT_INTERVAL,
  HOLLOW_MAN_P2_TELEPORT_INTERVAL,
  HOLLOW_MAN_P3_TELEPORT_INTERVAL,
  HOLLOW_MAN_PHANTOM_SHOT_DAMAGE,
  HOLLOW_MAN_PHANTOM_SHOT_SPEED,
  HOLLOW_MAN_GRAVE_REACH_DAMAGE,
  HOLLOW_MAN_GRAVE_REACH_RANGE,
  HOLLOW_MAN_AFTERIMAGE_HP,
  HOLLOW_MAN_AFTERIMAGE_LIFETIME,
  HOLLOW_MAN_DUST_VEIL_RADIUS,
  HOLLOW_MAN_DUST_VEIL_DURATION,
  HOLLOW_MAN_P2_STORM_DURATION,
  HOLLOW_MAN_P3_STORM_DURATION,
  HOLLOW_MAN_P2_STORM_VISIBILITY,
  HOLLOW_MAN_P3_STORM_VISIBILITY,
  HOLLOW_MAN_CONVERGENCE_SHOT_DAMAGE,
  HOLLOW_MAN_CONVERGENCE_COPIES,
  HOLLOW_MAN_CONVERGENCE_RECOVERY,
  HOLLOW_MAN_DISSOLVE_DURATION,
  HOLLOW_MAN_WAIT_DURATION,
  HOLLOW_MAN_ARRIVE_DURATION,
  HOLLOW_MAN_P1_PHANTOM_TELEGRAPH,
  HOLLOW_MAN_P2_PHANTOM_TELEGRAPH,
  HOLLOW_MAN_P3_PHANTOM_TELEGRAPH,
} from './hollowMan'

export {
  OLD_SCRATCH_HP,
  OLD_SCRATCH_RADIUS,
  OLD_SCRATCH_P1_SPEED,
  OLD_SCRATCH_P2_SPEED,
  OLD_SCRATCH_P3_SPEED,
  OLD_SCRATCH_P4_SPEED,
  OLD_SCRATCH_P1_COOLDOWN,
  OLD_SCRATCH_P2_COOLDOWN,
  OLD_SCRATCH_TRANSITION_IFRAMES,
  OLD_SCRATCH_P3_HEAL_HP,
  OLD_SCRATCH_P2_THRESHOLD,
  OLD_SCRATCH_P3_THRESHOLD,
  OLD_SCRATCH_P4_THRESHOLD,
  OLD_SCRATCH_COUNTER_WINDOW_DURATION,
  OLD_SCRATCH_COUNTER_INTERNAL_CD,
  OLD_SCRATCH_COUNTER_SIDESTEP_DIST,
  OLD_SCRATCH_COUNTER_SHOT_DAMAGE,
  OLD_SCRATCH_COUNTER_SHOT_SPEED,
  OLD_SCRATCH_P2_ROAD_SHRINK_TILES,
  OLD_SCRATCH_P3_ROAD_SHRINK_TILES,
} from './oldScratch'
