/**
 * Tilemap Data Structure
 *
 * Efficient tile-based map storage for collision detection.
 * Designed to work identically on client and server.
 */

import type { MapObstacle } from './content/maps/mapObstacleDefs'

/** Supported stage base-tile styles */
export const BASE_TILE_STYLES = ['red_dirt', 'grass', 'stone', 'crossroads_dirt'] as const
export type BaseTileStyle = (typeof BASE_TILE_STYLES)[number]

/** Number of base-tile variants per style in base_tileset.png */
export const BASE_TILE_VARIANTS_PER_STYLE = 6

/**
 * Stage base-tile rendering metadata.
 *
 * This is presentation metadata used by the client renderer; simulation and
 * collision continue to use TileType values.
 */
export interface BaseTileMetadata {
  style: BaseTileStyle
  variantCount: number
  seed: number
}

/**
 * A horizontal skip zone used for cross alleys and the center clear zone.
 * Buildings are not placed in these Y ranges, creating corridors.
 */
export interface SkipZone {
  /** Inclusive minimum Y tile */
  minY: number
  /** Exclusive maximum Y tile */
  maxY: number
}

/**
 * A cross alley with per-column bending profile.
 */
export interface AlleyProfile {
  /** Per-column center Y (length = map width) */
  profile: number[]
  /** Alley width in tiles (2 or 3) */
  width: number
  /** Bounding envelope from min/max of profile ± width */
  bounds: SkipZone
}

/**
 * A short spur road branching off the main street.
 */
export interface SpurRoad {
  /** Y position of the spur (top row) */
  y: number
  /** Width in tiles (height of spur = SPUR_WIDTH) */
  height: number
  /** Starting X (from main street edge) */
  startX: number
  /** Length in tiles (extending outward from street) */
  length: number
  /** Direction: -1 = west, +1 = east */
  direction: -1 | 1
}

/**
 * Complete road network with meandering profiles.
 */
export interface RoadNetwork {
  /** Base center X for building placement (fixed) */
  streetCenterX: number
  /** Per-row center X for the main street (length = map height) */
  streetProfile: number[]
  /** Cross alleys with per-column bending profiles */
  alleys: AlleyProfile[]
  /** Bounding skip zones derived from alley profiles */
  crossAlleyBounds: SkipZone[]
  /** Short spur roads branching off main street */
  spurs: SpurRoad[]
}

/**
 * A building placed by the map generator.
 * Stored on the Tilemap so the client can render building sprites.
 */
export interface PlacedBuilding {
  /** Building profile ID (maps to sprite region on client) */
  profileId: string
  /** Top-left tile X of the collision footprint */
  tileX: number
  /** Top-left tile Y of the collision footprint */
  tileY: number
}

/**
 * A single layer of tiles
 */
export interface TileLayer {
  /** Tile data as flat array (row-major order) */
  data: Uint8Array
  /** Whether this layer blocks movement */
  solid: boolean
}

/**
 * Complete tilemap with dimensions and layers
 */
export interface Tilemap {
  /** Width in tiles */
  width: number
  /** Height in tiles */
  height: number
  /** Size of each tile in pixels */
  tileSize: number
  /** Map layers (bottom to top) */
  layers: TileLayer[]
  /** Incremented by dynamic tile modification APIs to signal renderer invalidation */
  tileVersion: number
  /** Optional base-tile visual metadata for stage-aware rendering */
  baseTiles?: BaseTileMetadata
  /** Buildings placed by the map generator (for client rendering) */
  placedBuildings?: PlacedBuilding[]
  /** Cross alley corridors generated by the road network.
   *  Used by obstacle placement to reject obstacles inside alleys,
   *  and exposed for tests and debug rendering. */
  crossAlleys?: SkipZone[]
  /** Full road network with meandering profiles (for tests and debug). */
  roadNetwork?: RoadNetwork
  /** Map obstacles generated during arena generation */
  mapObstacles?: MapObstacle[]
  /** Crossroads arena landmark positions (Stage 4 only) */
  crossroadsLandmarks?: CrossroadsLandmarks
}

/**
 * Landmark positions for the crossroads arena (Stage 4).
 * All positions are in world coordinates (pixels).
 */
export interface CrossroadsLandmarks {
  /** Center signpost position */
  signpost: { x: number; y: number }
  /** Four lantern positions at the corners of the center clearing */
  lanterns: Array<{ x: number; y: number }>
  /** Four road endpoint positions (spawn points for Ghost Riders) */
  roadEndpoints: Array<{ x: number; y: number }>
}

/** Tile type constants */
export const TileType = {
  EMPTY: 0,
  WALL: 1,
  FLOOR: 2,
  LAVA: 3,
  HALF_WALL: 4,
  MUD: 5,
  BRAMBLE: 6,
  WOOD_FLOOR: 7,
  ROAD: 8,
  BRIMSTONE: 9,
  DARKNESS: 10,
} as const

export type TileTypeValue = (typeof TileType)[keyof typeof TileType]

/**
 * Create an empty tilemap
 */
export function createTilemap(
  width: number,
  height: number,
  tileSize: number
): Tilemap {
  return {
    width,
    height,
    tileSize,
    layers: [],
    tileVersion: 0,
  }
}

/**
 * Add a layer to the tilemap
 */
export function addLayer(map: Tilemap, solid: boolean): TileLayer {
  const layer: TileLayer = {
    data: new Uint8Array(map.width * map.height),
    solid,
  }
  map.layers.push(layer)
  return layer
}

/**
 * Get tile index from tile coordinates
 */
export function tileIndex(map: Tilemap, tileX: number, tileY: number): number {
  return tileY * map.width + tileX
}

/**
 * Get tile value at tile coordinates
 */
export function getTile(
  map: Tilemap,
  layerIndex: number,
  tileX: number,
  tileY: number
): number {
  const layer = map.layers[layerIndex]
  if (!layer) return 0

  if (tileX < 0 || tileX >= map.width || tileY < 0 || tileY >= map.height) {
    return 0
  }

  return layer.data[tileIndex(map, tileX, tileY)] ?? 0
}

/**
 * Set tile value at tile coordinates
 */
export function setTile(
  map: Tilemap,
  layerIndex: number,
  tileX: number,
  tileY: number,
  value: number
): void {
  const layer = map.layers[layerIndex]
  if (!layer) return

  if (tileX < 0 || tileX >= map.width || tileY < 0 || tileY >= map.height) {
    return
  }

  layer.data[tileIndex(map, tileX, tileY)] = value
}

/**
 * Convert world coordinates to tile coordinates
 */
export function worldToTile(
  map: Tilemap,
  worldX: number,
  worldY: number
): { tileX: number; tileY: number } {
  return {
    tileX: Math.floor(worldX / map.tileSize),
    tileY: Math.floor(worldY / map.tileSize),
  }
}

/**
 * Convert tile coordinates to world coordinates (top-left corner)
 */
export function tileToWorld(
  map: Tilemap,
  tileX: number,
  tileY: number
): { worldX: number; worldY: number } {
  return {
    worldX: tileX * map.tileSize,
    worldY: tileY * map.tileSize,
  }
}

/**
 * Check if a world position is inside a solid tile
 *
 * Checks all solid layers for collision.
 */
export function isSolidAt(map: Tilemap, worldX: number, worldY: number): boolean {
  const { tileX, tileY } = worldToTile(map, worldX, worldY)

  // Out of bounds is solid (prevents escaping the map)
  if (tileX < 0 || tileX >= map.width || tileY < 0 || tileY >= map.height) {
    return true
  }

  // Check all solid layers
  for (let i = 0; i < map.layers.length; i++) {
    const layer = map.layers[i]
    if (!layer || !layer.solid) continue

    const tile = layer.data[tileIndex(map, tileX, tileY)]
    if (tile !== undefined && tile !== TileType.EMPTY) {
      return true
    }
  }

  return false
}

/**
 * Get the exact solid tile type at a world position.
 *
 * Returns TileType.EMPTY when no solid tile is present.
 * Out-of-bounds positions are treated as TileType.WALL.
 */
export function getSolidTileTypeAt(map: Tilemap, worldX: number, worldY: number): number {
  const { tileX, tileY } = worldToTile(map, worldX, worldY)

  if (tileX < 0 || tileX >= map.width || tileY < 0 || tileY >= map.height) {
    return TileType.WALL
  }

  for (let i = 0; i < map.layers.length; i++) {
    const layer = map.layers[i]
    if (!layer || !layer.solid) continue

    const tile = layer.data[tileIndex(map, tileX, tileY)]
    if (tile !== undefined && tile !== TileType.EMPTY) {
      return tile
    }
  }

  return TileType.EMPTY
}

/**
 * Get the floor tile type at a world position.
 *
 * Returns the first non-empty tile found in non-solid layers.
 */
export function getFloorTileTypeAt(map: Tilemap, worldX: number, worldY: number): number {
  const { tileX, tileY } = worldToTile(map, worldX, worldY)

  if (tileX < 0 || tileX >= map.width || tileY < 0 || tileY >= map.height) {
    return TileType.EMPTY
  }

  for (let i = 0; i < map.layers.length; i++) {
    const layer = map.layers[i]
    if (!layer || layer.solid) continue

    const tile = layer.data[tileIndex(map, tileX, tileY)]
    if (tile !== undefined && tile !== TileType.EMPTY) {
      return tile
    }
  }

  return TileType.EMPTY
}

/**
 * Get the AABB bounds of a tile in world coordinates
 */
export function getTileBounds(
  map: Tilemap,
  tileX: number,
  tileY: number
): { minX: number; minY: number; maxX: number; maxY: number } {
  return {
    minX: tileX * map.tileSize,
    minY: tileY * map.tileSize,
    maxX: (tileX + 1) * map.tileSize,
    maxY: (tileY + 1) * map.tileSize,
  }
}

/**
 * Get all tiles that a circle potentially overlaps
 */
export function getTilesInCircle(
  map: Tilemap,
  centerX: number,
  centerY: number,
  radius: number
): Array<{ tileX: number; tileY: number }> {
  const tiles: Array<{ tileX: number; tileY: number }> = []

  // Get bounding box of circle in tile coordinates
  const minTileX = Math.floor((centerX - radius) / map.tileSize)
  const maxTileX = Math.floor((centerX + radius) / map.tileSize)
  const minTileY = Math.floor((centerY - radius) / map.tileSize)
  const maxTileY = Math.floor((centerY + radius) / map.tileSize)

  for (let ty = minTileY; ty <= maxTileY; ty++) {
    for (let tx = minTileX; tx <= maxTileX; tx++) {
      tiles.push({ tileX: tx, tileY: ty })
    }
  }

  return tiles
}

/**
 * Get the playable bounds of a tilemap (one tile inset from edges).
 */
export function getPlayableBoundsFromTilemap(map: Tilemap): {
  minX: number
  minY: number
  maxX: number
  maxY: number
} {
  return {
    minX: map.tileSize,
    minY: map.tileSize,
    maxX: (map.width - 1) * map.tileSize,
    maxY: (map.height - 1) * map.tileSize,
  }
}

/**
 * Get the center of a tilemap in world coordinates.
 */
export function getArenaCenterFromTilemap(map: Tilemap): { x: number; y: number } {
  return {
    x: (map.width * map.tileSize) / 2,
    y: (map.height * map.tileSize) / 2,
  }
}

// ============================================================================
// Dynamic tile modification (for mid-encounter arena changes)
// ============================================================================

/**
 * Set a tile type at grid coordinates on a specific layer.
 * Used for mid-encounter arena changes (arena shrink, brimstone placement).
 * Increments tileVersion to signal renderer invalidation.
 */
export function setTileAt(
  map: Tilemap,
  layerIndex: number,
  tileX: number,
  tileY: number,
  type: TileTypeValue,
): void {
  setTile(map, layerIndex, tileX, tileY, type)
  map.tileVersion++
}

/**
 * Convert a rectangular range of tiles to a different type.
 * Inclusive on all bounds. Used for arena shrinking (FLOOR → WALL)
 * and brimstone crack placement (FLOOR → BRIMSTONE).
 */
export function collapseTileRange(
  map: Tilemap,
  layerIndex: number,
  minTileX: number,
  minTileY: number,
  maxTileX: number,
  maxTileY: number,
  newType: TileTypeValue,
): void {
  const clampMinX = Math.max(0, minTileX)
  const clampMinY = Math.max(0, minTileY)
  const clampMaxX = Math.min(map.width - 1, maxTileX)
  const clampMaxY = Math.min(map.height - 1, maxTileY)

  for (let y = clampMinY; y <= clampMaxY; y++) {
    for (let x = clampMinX; x <= clampMaxX; x++) {
      setTile(map, layerIndex, x, y, newType)
    }
  }
  map.tileVersion++
}
